### ISSUE TITLE
Define top-level init args

### ISSUE THREAD

**Issue by stresslimit** [FoxComm/api-js#6]
What should we require & allow to pass to API lib to config init? I've taken a first pass here, with either `required` or default value:

``` yaml
api_url: required
prefix: '/api'
version: 'v1'
public_key: required
```
